require 'spec_helper'
require 'puppet/pops'
require 'puppet/pspec'

describe 'Running parser.pspec' do
  compiler = Puppet::Parser::Compiler.new(
    Puppet::Node.new('pspec_test', :environment => Puppet::Node::Environment.create(:testing, [])))
  examples = compiler.with_context_overrides('pspec evaluation') do
    scope = compiler.topscope
    Puppet::PSpec.init(scope)
    Puppet::PSpec.load_examples(scope, my_fixture('parser.pspec'))
  end

  # test_framework is passed as the test framework to the tests generated by pspec. This vouches for
  # correct rspec output where Examples becomes "context" and Example becomes "it".
  test_framework = Puppet::PSpec::TestFramework.create(self)

  examples.each do |pspec_test|
    Puppet::PSpec::Context.run_test(pspec_test, nil, test_framework)
  end
end
